### ISSUE TITLE
Ability to add custom text to the attaintment section

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#100]
Near 'attainment' we need to be able to set text like:

IMPORTANT: All marks/grades indicated with '**' are subject to moderation and confirmation by a Board of Examiners. These marks/grades are therefore provisional and subject to change.

on an institution basis.

I think this is the first actually real customisation request, so I'll flesh out the detail, but the idea is the customisation is set in Data Explorer, and the app calls an API to get the detail.

Will flesh out later, but need to do this one quickly.

@TherapyBox can you think how this would work from a design perspective?

**Comment by michaelwebbjisc** [comment]
Add API call to get the text.

**Comment by tomglanville** [comment]
This has been hard-coded for glos. See below screenshot from Android version (iOS not yet pushed):

<img src="<img src="https://cloud.githubusercontent.com/assets/5815497/24365906/5d6da340-130f-11e7-9027-e8f2bdb2eec9.png" width="300">" width="300">

**Comment by tomglanville** [comment]
Have published this to Google Play Store (1.0.4).

**Comment by tomglanville** [comment]
TB still waiting for API call.
