### ISSUE TITLE
Add Demo Mode

### ISSUE THREAD

**Issue by mparker-tbox** [jiscdev/study-goal#101]
Button with "demo mode" on the login page, takes user through to a version of the app filled with dummy data. All user journeys should be possible, but none of the user generated data is saved.

**Comment by michaelwebbjisc** [comment]
I've got an idea on how to do this from an api perspective.  Basically I'll create a token that never expires (fine as it won't access really data).  I'll then ammend the api to return plausible data for the data calls for that token.  I've not done this yet, but when it's done I put details of the token on basecamp.

**Comment by mparker-tbox** [comment]
We thought we'd just hard code dummy data into the app, this way it can also work offline. Either way is fine by us though.

**Comment by mparker-tbox** [comment]
Have spoken with Tom about this. Will use a token as you suggested. Do we need to do anything with, for example, Activity data, targets etc for dummy user or will you be able to populate this from your side okay?

**Comment by michaelwebbjisc** [comment]
ok, i'll look at setting up the demo data today.  I'll drop something later on how to test it.

**Comment by michaelwebbjisc** [comment]
I've just posted details of the test data in basecamp.  It should work now - let me know.

**Comment by tomglanville** [comment]
Seems to be working on both platforms. Will roll out in v1.0.3.
