### ISSUE TITLE
Email appears as not@known

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#104]
Android:
<img src="https://cloud.githubusercontent.com/assets/5815497/23359909/77c3f1c6-fce0-11e6-9806-4727d4ce7646.png" width="400">

iOS:
<img src="https://cloud.githubusercontent.com/assets/5815497/23359914/79e2b3c0-fce0-11e6-82c9-7c5f0f058a32.png" width="400">

**Comment by michaelwebbjisc** [comment]
ah, that's probably just because you've not got an email address set in the test data in UDD.  I'll check.

**Comment by michaelwebbjisc** [comment]
(not@known is what the /student api returns if it can't find an email address)

**Comment by tomglanville** [comment]
I see, the iOS screenshot was taken from one of the students (which was why I obfuscated their name/id).

**Comment by michaelwebbjisc** [comment]
ah, is it strathcylde?  They haven't provided email addresses.

**Comment by tomglanville** [comment]
There is a student from Glos that also has this issue

**Comment by michaelwebbjisc** [comment]
Can you try calling:

https://sp.data.alpha.jisc.ac.uk/student

with the token in authorization header and see what it gives.

**Comment by tomglanville** [comment]
Understand this will be fixed once glos update their data.

**Comment by tomglanville** [comment]
TB to make suggestions to Paul on this issue.

**Comment by JemmaGreener** [comment]
Can we send blank string instead of not@known? @pbailey64 are you happy with this being blank if no email is attached?

**Comment by pbailey64** [comment]
yes - blank is ok

**Comment by TherapyBox** [comment]
done in iOS

**Comment by tomglanville** [comment]
Not working on iOS on develop or ui_updates. Can you mention which branch the issue is resolved on? Will save me a bit of time when testing

**Comment by tomglanville** [comment]
Not working on Android develop branch either, unable to test on ui_updates as it doesn't navigate me into app after auth.

**Comment by TherapyBox** [comment]
should now be resolved on iOS --> UI_updates (was functioning in the navigation drawer, but missed in settings -- now hidden in both places)

**Comment by tomglanville** [comment]
Ok, once I'm able to test on Android I'll close this

**Comment by TherapyBox** [comment]
Resolved on both iOS and Android, (we've also fixed android so it doesn't show "|" in settings, if there's no email address, but this isn't updated on develop just yet)

**Comment by tomglanville** [comment]
Done
