### ISSUE TITLE
Different modules load for each platform (also no engagement graph data on Android)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#107]
Have logged in as the same user (myself) across both platforms and noticed discrepancies. This issue appears to impact other users as well.

iOS modules:
<img src="https://cloud.githubusercontent.com/assets/5815497/23467750/c410b3fe-fe96-11e6-9029-ec553781908c.png" width="400">

Android modules:
<img src="https://cloud.githubusercontent.com/assets/5815497/23467668/9354c804-fe96-11e6-8e2e-e5d3c793c2ab.png" width="400">

Android (lack of) data:
<img src="https://cloud.githubusercontent.com/assets/5815497/23467697/a2bb51be-fe96-11e6-926f-f9c1e7183323.png" width="400">

**Comment by michaelwebbjisc** [comment]
I can see what's happening, but not why.  On iOS you are signed in as staff member, so you get the dummy data that staff are supposed to get.  On Android you are signed as a student to Jisc, so you get the fake modules assigned to your fake Jisc student account.

**Comment by tomglanville** [comment]
In that case it's probably to do with how I'm bypassing the login (on iOS it prompts me to register for some reason so I bypass that page)... have unassigned from therapy box for now

**Comment by tomglanville** [comment]
Apologies, my mistake - I had changed the way the login worked and tricked it into thinking I was staff.
