### ISSUE TITLE
Make staff login option more prominent

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#108]
A few staff members have had issues logging in, this is likely because they are forgetting to tick the staff member box.

Can we make this option more prominent - perhaps include [student | staff ] within a segmented control?

Example below:
<img src="https://maniacdev.com/wp-content/uploads/2014/05/NYSegmentedControl-2.png" width="300">

**Comment by michaelwebbjisc** [comment]
Add to feature branch.

**Comment by tomglanville** [comment]
Branch **feature/login-page-update** added on both platforms

**Comment by tomglanville** [comment]
TG to demo to Paul and get PO feedback.

**Comment by tomglanville** [comment]
TB to work with Paul - this to move to next milestone

**Comment by tomglanville** [comment]
I tested login_v2 branch and it fails to load the background image on the login page on mobile devices. The image is called tmp_login_background.jpg and is 2048x1536. 

The reason is that the image is taking too much memory: 
https://stackoverflow.com/questions/38308292/imageview-displays-png-but-not-jpeg

I got the image to display by re-sizing to 512x384. Please can @TherapyBox look into this to ensure it works well on tablet and phone?

**Comment by tomglanville** [comment]
Is now fixed and part of develop branch (android)

**Comment by tomglanville** [comment]
Updated login page now part of develop branch on both platforms:
https://github.com/jiscdev/study-goal-android/pull/6
https://github.com/jiscdev/study-goal-ios/pull/3
