### ISSUE TITLE
Unable to access attainment data for students from Oxford Brooks

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#115]
This issue is preventing attainment grades from showing is because the API is only using 'ASSESS_AGREED_GRADE' but Brookes are using 'ASSESS_AGREED_MARK'.

**Comment by tomglanville** [comment]
> it looks like the API is only using 'ASSESS_AGREED_GRADE' but Brookes are using 'ASSESS_AGREED_MARK'

**Comment by michaelwebbjisc** [comment]
should be resolved now @tomglanville can you arrange a test?

**Comment by tomglanville** [comment]
Will do

**Comment by tomglanville** [comment]
Appears to be broken for all of the students I've tried (different institutions)

**Comment by tomglanville** [comment]
Oxford Brooks is working for the student I tested however

**Comment by tomglanville** [comment]
This is now working - module and grade sent as strings. No app release required as this was a data change.
