### ISSUE TITLE
Update attainment disclaimer text

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#123]
Changes 'marksgrades' to 'marks / grades'. Occurs multiple times.

**Comment by mparker-tbox** [comment]
Should be available for both now

**Comment by tomglanville** [comment]
Text appears to have ellipsis on grades that are marked with '**'.

<img src="https://cloud.githubusercontent.com/assets/5815497/24495891/82af80f8-152e-11e7-85d1-61df99d054f0.png" width="300">

**Comment by tomglanville** [comment]
Am still seeing this popup on the stats page. I believe this may have been fixed in develop - if so can we merge the latest develop into the feature/attainment-disclaimer branch? That way I can do a release once the issue above is also fixed.

<img src="https://cloud.githubusercontent.com/assets/5815497/24495945/b6746a98-152e-11e7-8513-d1faffd9f947.png" width="300">

**Comment by tomglanville** [comment]
Both issues appear to be fixed. Have released update for Android (1.0.5). Will do same for iOS
