### ISSUE TITLE
Allow other applications to launch study goal (was Add url scheme)

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#127]
ie allow other applications to launch study goal

**Comment by mparker-tbox** [comment]
This has been added and updated in a separate branch

**Comment by tomglanville** [comment]
TB to check why this wasn't on ios repo.

**Comment by pbailey64** [comment]
Question from Phil Thorman "“Could this be done for Collabco too - they have 24 universities signed up for their platform, though not sure yet of overlap with LA”. Will the approach being implemented work with other student apps similar to CampusM?

**Comment by pbailey64** [comment]
Collabco’s Myday platform offers:

1.	Simple links out to other systems / URLs (but would this work with an app?)
2.	Integrating apps (requires HTML and JS skills)

**Comment by tomglanville** [comment]
The app can be opened by navigating to **studygoal://** via the browser on iOS (the app must already be installed).
The app can be opened by navigating to **jisc://studygoal** via the browser on Android (the app must already be installed).

**Comment by tomglanville** [comment]
These features have now been merged into develop:
https://github.com/jiscdev/study-goal-android/pull/5
https://github.com/jiscdev/study-goal-android/pull/5
