### ISSUE TITLE
Android engagement graph doesn't render correctly

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#13]
When logging as Duns the call:
https://app.analytics.alpha.jisc.ac.uk/graph/engagement?scope=7d&module=LA101-1-2016S1-0

returns:

{"0":34,"-1":59,"-2":69,"-3":44,"-4":69,"-5":64,"-6":91}

This is rendered correctly in iOS but not Android.  Screenshots attached

![android](https://cloud.githubusercontent.com/assets/8233360/16043684/d1be35ce-3238-11e6-9c80-bec511212828.png)

![ios](https://cloud.githubusercontent.com/assets/8233360/16044356/079af256-323c-11e6-99bc-a90dc77a5a32.PNG)

**Comment by TherapyBox** [comment]
We'll fix this.

**Comment by robwynj** [comment]
Need an update here @TherapyBox
