### ISSUE TITLE
Direct link to settings if location services is turned off (check-in page)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#130]
This is to allow students to easily turn on location services from within the app. Location services helps verify students are in the lecture.

This was noted during the check-in demo with glos on 07/04/17.

Examples:
```
In Swift:
UIApplication.sharedApplication().openURL(NSURL(string:UIApplicationOpenSettingsURLString)!)

In Objective-C
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
```

**Comment by tomglanville** [comment]
@TherapyBox  please confirm what branch this is in.

**Comment by tomglanville** [comment]
Appears to work as expected on iOS (check-in branch).

Not sure it works on Android - app doesn't seen to request the location permission in the manifest file. @TherapyBox Can you comment on this?

**Comment by mparker-tbox** [comment]
Hi. Looks to be an issue here, so we're resolving today
