### ISSUE TITLE
'Demo' at top of institution list causes error

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#131]
Please remove this option from the top of the list. Noticied on iOS **feature/demo-mode-fix** branch.

<img src="https://cloud.githubusercontent.com/assets/5815497/24860116/0014e9c4-1deb-11e7-8954-3bdc05cb4840.png" width="400">

**Comment by tomglanville** [comment]
As noted during meeting on 12/04/17 the 'demo' option at the top of list only appears after the user has logged into the app/demo mode at least once.

**Comment by mparker-tbox** [comment]
Appears fixed, but will do further testing
