### ISSUE TITLE
Scale photo (either from camera or device storage) prior to profile picture edit

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#133]
Scale to something like 1000x1000 prior to upload (maintain aspect). This should help resolve freshdesk issue 16 (app not handling large file upload very well).

**Comment by mparker-tbox** [comment]
updated on develop branch, but needs further testing.

**Comment by tomglanville** [comment]
It appears this is an issue on Android which images around 1mb in size.

**Comment by michaelwebbjisc** [comment]
Feature ready for release: -> Develop Branch

**Comment by tomglanville** [comment]
Rob B (tester) noticed profile pictures appear low-quality/grainy on Android. Apart from that this update appears to have improved picture upload times.
