### ISSUE TITLE
Add timeout to profile picture upload and progress bar (20s)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#134]
This links to #133 to enable the app to handle large photo uploads better.

**Comment by mparker-tbox** [comment]
updated via github, but needs further testing

**Comment by michaelwebbjisc** [comment]
Pass to tester

**Comment by tomglanville** [comment]
Rob B (tester) noticed no issues.

@mparker-tbox Can you confirm where in the code the 20 second timeout is declared? I'm unable to find it. Apart from that this looks complete.

**Comment by TherapyBox** [comment]
Time out is 10S. Timeout gets declared in network manager.

**Comment by tomglanville** [comment]
Believe is was set to 10 seconds in Android (NetworkManager.java line 73). Have updated.
