### ISSUE TITLE
Therapy Box to use jisc certificates for push notificiations

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#138]
This is a blocker on release 1.1.0 being on time.

**Comment by michaelwebbjisc** [comment]
What do we need to do for this one?

**Comment by tomglanville** [comment]
We need to supply @TherapyBox with the Apple Push Services certificates that I created on behalf of the Jisc account (which I've done).

They will need to upload the certificate to whoever is handling their push notifications, which I believe is [Google](https://developers.google.com/cloud-messaging/)
