### ISSUE TITLE
Institutions need to be listed according to UKAccessFederation conventions

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#141]
Institutions need to listed according to UKAccessFederation naming conventions i.e. full inst name.

I believe we manage the API endpoint for the list - see here:
https://app.analytics.alpha.jisc.ac.uk/idps

@pbailey64 Do you know what these should be? Then I assume it will be relatively simple to update the list.

**Comment by tomglanville** [comment]
@pbailey64 Do you know the correct format for these? This might be something we hard-code into the app as a quick-fix.

**Comment by TherapyBox** [comment]
Not resolved yet. Will sort out a lookup system tomorrow.

**Comment by TherapyBox** [comment]
Done for iOS

**Comment by tomglanville** [comment]
@pbailey64 Are you happy with this as the format? 
@TherapyBox Could we have South Wales over 2 lines to prevent the cut-off?
<img src="https://user-images.githubusercontent.com/5815497/28713571-723cbf8a-7387-11e7-84ac-4f8f00093771.png" width="300">

**Comment by TherapyBox** [comment]
Resolved in iOS and android.

**Comment by TherapyBox** [comment]
done in iOS and Android

**Comment by tomglanville** [comment]
Done
