### ISSUE TITLE
Unable to navigate back to login screen from institution screen

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#142]
For example, if you accidentally tap 'staff' instead of 'student' you will need to close the app in order to go back to the original page that contains the options.

<img src="https://user-images.githubusercontent.com/5815497/27480828-b43b4ea6-5811-11e7-8e9f-6325f05ee2de.png" width="400">

**Comment by TherapyBox** [comment]
Resolved on both iOS and Android

**Comment by tomglanville** [comment]
Tested on both platforms.
