### ISSUE TITLE
Please revert the demo user profile picture back to jisc logo

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#143]
I believe this has been changed by testing an older version of the app. The current live version of the app doesn't allow the demo user to change the picture. Can we change this back to the jisc logo please?

**Comment by awang-box** [comment]
done. This has been fixed in new branches so 1.1.1 update should prevent users from being able to change the image back again. 

Do you have user id and JWT for demouser2 incidentally? At the moment there is a blank image for this user and it may be good to have a different image for this.

**Comment by mparker-tbox** [comment]
done. This has been fixed in new branches so 1.1.1 update should prevent users from being able to change the image back again.

Do you have user id and JWT for demouser2 incidentally? At the moment there is a blank image for this user and it may be good to have a different image for this.

**Comment by tomglanville** [comment]
Do we manage demouser2 - do you know which institution they are a part of? I thought the demo data was handled by TB but I may be wrong

**Comment by mparker-tbox** [comment]
Demo data coming from automatically generated data at your side (for xAPI to be available). We can add faked data from our side if needed, but i think this was dismissed previously.

**Comment by tomglanville** [comment]
Have given you details for demouser2.
