### ISSUE TITLE
App to point to privacy statement

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#146]
@TherapyBox Will point to privacy statement URL provided by Jisc.
@pbailey64 We need to create and host privacy statement (and let TB know URL).

**Comment by pbailey64** [comment]
Ok - Michael suggested we create this in the github wiki https://github.com/jiscdev/learning-analytics/wiki Do you have access to create a page them we will need to look at writing a security statement.

**Comment by tomglanville** [comment]
Yes I can create a page once we have the content ready

**Comment by pbailey64** [comment]
Create a blank page, then you will have URL and TB can implement

**Comment by tomglanville** [comment]
https://github.com/jiscdev/learning-analytics/wiki/Privacy-Statement

**Comment by TherapyBox** [comment]
Resolved but github link isn't responsive. Could benefit from a different page.
Header in iOS isn't ideal, will change the title. Will also change image so that it isn't the same as language settings.

**Comment by TherapyBox** [comment]
Some android tabs are crashing when i try to enter settings, so will fix this.

**Comment by pbailey64** [comment]
Can we live with this link for now and change it later?

**Comment by TherapyBox** [comment]
Yes. It will still be readable and changing the link isn't a big deal, just wanted to give a heads up on this in case it was a problem, but we're fine leaving it as it is for now.

**Comment by tomglanville** [comment]
Tested on develop branch - iOS issues:

Please update text to Privacy Statement:
<img src="https://user-images.githubusercontent.com/5815497/28711477-9658770e-737f-11e7-91c6-806742eeb62a.png" width="400">

Title should be Privacy Statement too:
<img src="https://user-images.githubusercontent.com/5815497/28711481-97965dc0-737f-11e7-981a-2240d4caad6b.png" width="400">

**Comment by TherapyBox** [comment]
Listed in Localisable strings under "consent" as we re-used parts of the old consent statement section. We can rename everywhere to privacyStatement or similar if this is preferred. We're also building in a separate link for welsh in case you want to link to a welsh language version of the statment.
