### ISSUE TITLE
Photo incredibly grainy when taken from Android device

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#147]
Please can we reduce the compression on the photos - too grainy at the moment.
Photos selected from the library also appear rotated by 90'.
Tested on Samsung S6 physical device.

Photo capture:
<img src="https://user-images.githubusercontent.com/5815497/28213104-8a9777d2-689c-11e7-843a-c119a528ff48.png" width="300">

Library selection:
<img src="https://user-images.githubusercontent.com/5815497/28213110-8c6b48cc-689c-11e7-8d97-9bd3687941b8.png" width="300">

**Comment by TherapyBox** [comment]
Resolved in develop branch

**Comment by tomglanville** [comment]
Photo has improved.
