### ISSUE TITLE
Stats page default to 7d graph (it shows 30d)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#153]
Mismatch between selected option and graph content - see image.

![simulator screen shot 7 aug 2017 14 55 09](https://user-images.githubusercontent.com/5815497/29029688-72414c8e-7b80-11e7-967c-f8dd28aaea56.png)

**Comment by TherapyBox** [comment]
Changed the default highlight to 28d but can revert default back to 7d view and switch the highlight back if preferred

**Comment by tomglanville** [comment]
Fixed - TB will fix title issue today as well
