### ISSUE TITLE
Privacy Policy web page issues

### ISSUE THREAD

**Issue by pbailey64** [jiscdev/study-goal#155]
Two issues to resolve. 
First the page needs to point at a better page than the githuib wiki, at least it should be the public view https://docs.analytics.alpha.jisc.ac.uk/docs/learning-analytics/Privacy-Statement

Second we need it to support language selection, so point at Welsh version if that language is selected

**Comment by TherapyBox** [comment]
This is ready in both iOS and android we just need updated links
