### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by pbailey64** [jiscdev/study-goal#156]
Users need to agree to the Terms and Conditions of use when they first login to the app.
Mark/Paul are working on the T&Cs and these can again be a link to the github wiki 
https://docs.analytics.alpha.jisc.ac.uk/docs/learning-analytics/App-service-terms-and-conditions

**Comment by pbailey64** [comment]
Revised URL https://docs.analytics.alpha.jisc.ac.uk/docs/study-goal/App-service-terms-and-conditions

**Comment by tomglanville** [comment]
Done
