### ISSUE TITLE
Update menu items

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#158]
Points should be Activity points.
Graphs VLE Activity should be VLE Activity, etc.

**Comment by TherapyBox** [comment]
Have updated to:
VLE Activity
Attainment
Activity Points
Engagement Leaderboard
Events Attended (not currently being shown)
Attendance Summary 


Let me know if any of these are incorrect and we'll change

**Comment by tomglanville** [comment]
Fixed
