### ISSUE TITLE
Welsh Translations - Trophy Descriptions (Missing) - iOS

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#18]
FAO @TherapyBox

**Comment by TherapyBox** [comment]
I'll see if i can find and send over

**Comment by robwynj** [comment]
FAO TB - are these now fixed? Kind Regards, Rob

**Comment by robwynj** [comment]
Hi @TherapyBox - have checked the welsh trophy naming/ descriptions -> can you confirm the contact for the "Carpal Tunnel" naming for someone who has done writing for a period of time - should it be something different?! I would name it something like "Ysgrifennwr Prysyr" or "Busy Writer" or "Busy Writing" in english for example....

Otherwise, all other naming and descriptions are in for welsh (in iOS) - the above needs clarification/ correction.

Thoughts?

Rob

**Comment by mparker-tbox** [comment]
Change has been made on the server side, so should now be visible within the app.
