### ISSUE TITLE
Facebook link behaviour unexpected

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/study-goal#28]
clicking on the facebook link from the engagement graph offers me 'complete action using' but Browser is not one of the supported mechanisms. If I choose firefox I get a status message 'no link found in this share'.

When I click twitter, I get the expected 'twitter is not installed on this device' -- should I be getting the same for facebook if I don't have the facebook app?

**Comment by robwynj** [comment]
Will check this on Android version asap

**Comment by robwynj** [comment]
Hi Matthew,

The link to app selection seems to work now - @leebaylis can you test this (I'm not on facebook) to see if it does go through to posting dialog box within the app?

Matthew - any update on this issue with direct facebook linkage?

Kind Regards/ Many Thanks

Rob

**Comment by robwynj** [comment]
Confirmed - Matthew to use different icon (instead of facebook one) as a work-around, which will allow user to manually select app to link to. iOS does not have this issue with linking to facebook.
