### ISSUE TITLE
Share message not suitable for app-unaware public

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/study-goal#29]
The message is along the lines of 'x activity points sent from my jisc analytics app' -- has no detail (this week/overall) or context (what does the number mean) if it is going up on twitter or facebook.

How about 'this week my course engagement score is x compared to course average y (sent from my jisc analytics app)' or similar?

**Comment by TherapyBox** [comment]
I don't think we're getting a course average at the moment, no problem to change wording to give additional context, but we'd need a new call in order to gather this information, I think

**Comment by robwynj** [comment]
Update @TherapyBox - has the working been changed (cannot test android at the moment)
