### ISSUE TITLE
Filter Linkage Issue (Engagement Graphs)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#44]
1.  Filter
   To find student’s courses and modules we run https://app.analytics.alpha.jisc.ac.uk/v2/filter 
   Get back: 
   {"courses":[{"S000A":"BSc General"}],"instances":[{"LA101-1-2016S1-0":"BASIC LA 1"},{"LA102-1-2016S1-0":"BASIC LA 2"}]}
   Everything here looks fine, but when we try to use any of these instances to make engagement graphs we get back {
   "code": 522,
   "status": "error",
   "data": [],
   "message": "No such course"
   }
   We’re not exactly sure how to find a course that does work for engagement (we’ve been using LA000A-2016A) in tests outside of the app because we know it works, but we’ve been using LA101-1-2016S1-0 & LA102-1-2016S1-0 inside the app on the assumption that this is supposed to be the correct thing to use, which is why it’s not working properly in the app.

**Comment by mparker-tbox** [comment]
I think this was resolved?

**Comment by robwynj** [comment]
To be tested
