### ISSUE TITLE
CompareTo Linkage Issue (Engagement Graphs)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#45]
1.  CompareTo

CompareTo format changed but is not too problematic (previously comparison came back with the user’s data from the same call – now it’s just one set of data – we’ve built it so that the app first checks the user’s engagement then draws a comparison line).

Trying to compare  Craig to duns over 28 days, first run Craig by himself, then run the Duns comparison here: 

https://app.analytics.alpha.jisc.ac.uk/v2/engagement?compareTo=202&course=LA000A-2016A&scope=28d

Brings back
{
  "0": 0,
  "-1": 0,
  "-2": 0,
  "-3": 0,
  "-4": 0,
  "-5": 0,
  "-6": 0,
  "-7": 0,
  "-8": 0,
  "-9": 0,
  "-10": 0,
  "-11": 0,
  "-12": 0,
  "-13": 0,
  "-14": 0,
  "-15": 0,
  "-16": 0,
  "-17": 0,
  "-18": 0,
  "-19": 0,
  "-20": 0,
  "-21": 0,
  "-22": 0,
  "-23": 0,
  "-24": 0,
  "-25": 0,
  "-26": 80,
  "-27": 0
}

This data seems incorrect. Essentially even when craig and duns have different scores, the return from “CompareTo” above is always identical.

**Comment by mparker-tbox** [comment]
I think this is okay. Any issues?
