### ISSUE TITLE
Top 10 Linkage Issue (Engagement Graphs)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#46]
1.  Top 10
   https://app.analytics.alpha.jisc.ac.uk/v2/engagement?aggregate=top10&course=LA000A-2016A&scope=28d
   {
   "0": 0,
   "-1": 0,
   "-2": 0,
   "-3": 0,
   "-4": 0,
   "-5": 0,
   "-6": 0,
   "-7": 0,
   "-8": 0,
   "-9": 0,
   "-10": 0,
   "-11": 0,
   "-12": 0,
   "-13": 0,
   "-14": 0,
   "-15": 0,
   "-16": 0,
   "-17": 0,
   "-18": 0,
   "-19": 0,
   "-20": 0,
   "-21": 0,
   "-22": 0,
   "-23": 0,
   "-24": 0,
   "-25": 0,
   "-26": 80,
   "-27": 0
   }
   We weren’t sure about this because again, it always seems to match whichever user we have. This format is fine , though. We can again, run simple engagement for user and then run a top 10 comparison with same parameters. This is how it’s built in the app at the moment and it’s theoretically identical to doing it all in 1 call.

**Comment by mparker-tbox** [comment]
This seems fine now. Any issues?
