### ISSUE TITLE
Use Page-Based Navigation on Target Section

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#58]
This is likely an optional feature for a future release.

Reason: I went through the app a few times before I noticed the little popup at the bottom that says you can swipe left/right through your targets. See image below:

<img src="https://cloud.githubusercontent.com/assets/5815497/20672047/ca92ab46-b577-11e6-83fe-f5984ea1610c.png" width="300">

---

If we used a UIPageViewController it would be more obvious to users that they could swipe through their targets, they'd also get an idea for how many targets that had set. See generic example below:

<img src="http://www.appcoda.com/wp-content/uploads/2013/06/pageviewcontroller1.png" width="500">

**Comment by mparker-tbox** [comment]
Done
