### ISSUE TITLE
iOS - Should  notification of friend request, allow you to link to confirm/ decline the request?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#60]
[
![apperror2](https://cloud.githubusercontent.com/assets/16684142/20708795/8a8f968c-b629-11e6-9da3-05b3f075dcb8.png)
](url)

**Comment by mparker-tbox** [comment]
Suggest the following implementation:

Tapping on a newsfeed item saying that you have a new friend request should open a pop up. “Do you want to respond now?” 
Tapping yes takes you to the friend requests page. Tapping no closes the pop up.

Will need Welsh for “Do you want to respond now?”

**Comment by robwynj** [comment]
Yes that's fine - welsh text is: "Ydych eisiau ymateb nawr?"

Many Thanks

Rob

**Comment by mparker-tbox** [comment]
Done
