### ISSUE TITLE
"for" used in text for welsh version and "module" - incorrect (iOS)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#62]
[
![apperror4](https://cloud.githubusercontent.com/assets/16684142/20713279/92c5130c-b63f-11e6-89dd-24c5242372f8.png)
](url)

**Comment by robwynj** [comment]
Text is basically incorrect - english "module" included (welsh is "modiwl") - so text should be:

Adolygwyd am <hours> awr ar gyfer modiwl <module>

**Comment by mparker-tbox** [comment]
done
