### ISSUE TITLE
Overlapping text in "Setting" form/ screen (Android - Welsh)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goal#64]
Need to check the app here (for both Android and iOS), for any overlapping text within the GUIs (see in welsh version - the setting for the home screen, in Android - for "porthiant").

Also - need to be able to check consistency for text/ wording changes in welsh and english, that they are exactly the same for both iOS and Android versions.

**Comment by mparker-tbox** [comment]
Done
