### ISSUE TITLE
Time is not updated on the Activity Log screen when timing an activity

### ISSUE THREAD

**Issue by mparker-tbox** [jiscdev/study-goal#78]
On the Activity Log screen I can have an activity that's in progress (started from the target screen). The time displayed here is not updated. I remains the same until I refresh the screen.

Additionally, when I tap on the issue in list, it should take me through to the page with the timer running, as it is, i have to tap on the clock icon in the top right, which is not intuitive.

**Comment by michaelwebbjisc** [comment]
iOS or Android?

**Comment by mparker-tbox** [comment]
Android
