### ISSUE TITLE
Word - description appears at the bottom left of graphs

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#82]
Don't think this should be there.

**Comment by michaelwebbjisc** [comment]
See bottom right of graph here as an example:

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/149540976@N05/30649337163/in/dateposted-public/" title="sg-bug-39"><img src="https://c4.staticflickr.com/6/5688/30649337163_c1a8ce2fe8.jpg" width="281" height="500" alt="sg-bug-39"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by mparker-tbox** [comment]
done
