### ISSUE TITLE
Switch between bar chart and line icon is a block

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#83]
See:

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/149540976@N05/30649337163/in/dateposted-public/" title="sg-bug-39"><img src="https://c4.staticflickr.com/6/5688/30649337163_c1a8ce2fe8.jpg" width="281" height="500" alt="sg-bug-39"></a>

Look at the top right of the graph.  This is Android, Nexus 5x

**Comment by mparker-tbox** [comment]
done
