### ISSUE TITLE
Graph should fit on one screen - Android

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#84]
On a Nexus 5x, which has a pretty decent screen, the graph doesn't fix on one screen.  It would be much better if it did.

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/149540976@N05/31341943191/in/dateposted-public/" title="sg-bug-41"><img src="https://c8.staticflickr.com/6/5475/31341943191_64d4e8371a.jpg" width="281" height="500" alt="sg-bug-41"></a>

**Comment by michaelwebbjisc** [comment]
Agreed this is for 7 days or 1 month

**Comment by mparker-tbox** [comment]
This was resolved but is happening with staff login. We're re-resolving this and will have fixe by 17.02.17

**Comment by mparker-tbox** [comment]
Resolved from our side, although there's a small UI issue on bar graph that we're including in tomorrow's list of bug fixes.
