### ISSUE TITLE
Assessment Date doesn't show due date

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#85]
Its not clear whether this is the API or a display issue.  I'll investigate the API first.

**Comment by michaelwebbjisc** [comment]
Matthew has sent details of API call

**Comment by michaelwebbjisc** [comment]
Tie into queries https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/25

**Comment by mparker-tbox** [comment]
iOS and Android have been made to match here, let me know if further rework required.
