### ISSUE TITLE
Chart sizing issue when no data points are available

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#86]
The bar chart and graph components appear to only take up half of the screen width if there are no data points available. This issue was noticed on a Nexus 5 simulated device.

<img src="https://cloud.githubusercontent.com/assets/5815497/21616211/8c19b828-d1d8-11e6-9c89-cbe352093cee.png" width="300">
<img src="https://cloud.githubusercontent.com/assets/5815497/21616276/c26c0dcc-d1d8-11e6-916e-4edcec075319.png" width="300">

**Comment by mparker-tbox** [comment]
Resolved in iOS and Android
