### ISSUE TITLE
Create 'staff login' option

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#87]
This will mean having a "I'm a staff member" check box on the first screen.

The authentication flow with then be slightly different (there's a different url you need to use to authenticate).

**Comment by mparker-tbox** [comment]
Note for devs: Add code to staff identifier for the backend and student and staff could conceivably have same id

**Comment by mparker-tbox** [comment]
Assume demo module

**Comment by mparker-tbox** [comment]
Staff won't have modules on course. Assume at least that they are on a "Demo Module", generate ID.

**Comment by michaelwebbjisc** [comment]
@mparker-tbox you should be able to call the first step of the authentication for staff in the same way as students.  The change then, is when you get token you call:

https://sp.data.alpha.jisc.ac.uk/staff

instead of:

https://sp.data.alpha.jisc.ac.uk/student

with the token as before.  This should return details as follows:

{"FIRST_NAME":"Beth","LAST_NAME":"Kim","PRIMARY_EMAIL_ADDRESS":"Beth.Kim@uoj.jisc.ac.uk","APPSHIB_ID":"beth@test.ukfederation.org.uk","STAFF_ID":"5000"}

So it's the same as for a student but the STAFF_ID is their instead of STUDENT_ID.

**Comment by michaelwebbjisc** [comment]
I should have added, the test details are:

login as University of Jisc  as Beth with the usual test details:

https://www.ukfederation.org.uk/content/Documents/TestIdP

**Comment by mparker-tbox** [comment]
This is working at login stage. Some bugs arising in logs and targets section of the app. Looking to resolve by 17.0.2.17

**Comment by tomglanville** [comment]
@TherapyBox Did the bugs get fixed? Happy to close this issue if they are.

**Comment by mparker-tbox** [comment]
As far as we're aware we cleared all bugs here.
