### ISSUE TITLE
Login for non-participating institutions

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#88]

**Comment by mparker-tbox** [comment]
This is nearly done, but not properly implemented. Planning to fix by 17.02.17

**Comment by mparker-tbox** [comment]
This was also resolved, I think. We've been able to login from here with this, but it may benefit from further testing.

**Comment by tomglanville** [comment]
To be tested (TB).

**Comment by michaelwebbjisc** [comment]
Sprint 1.08 Feature complete.  If Twitter isn't going to work remove.
