### ISSUE TITLE
Ability to input hours and minutes manually when working with tasks [feature request]

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#91]
Client feedback: "When logging or setting tasks it can be a bit time consuming scrolling through selecting the hours and minutes. I think it would be worth having the option to type in the specified values."

Note: Will tag this correctly once I'm given access (become contributor).

**Comment by tomglanville** [comment]
@TherapyBox Believe this has been done now - although I have noticed a layout issue. See below timer cut off at bottom:

<img src="https://cloud.githubusercontent.com/assets/5815497/24114901/a63f1caa-0d99-11e7-8cb8-bc47b87741ad.png" width="300">

**Comment by tomglanville** [comment]
On iOS want to be able to manually input time when doing (Start Activity Now Timed)

**Comment by pbailey64** [comment]
Just looking at latest test version. 1.0.7 Log activity Time spent in IoS - could do with some space between numbers of words (hours and minutes). I can't type in numbers for above example "Remember to take a breath..."

**Comment by mparker-tbox** [comment]
Which iPhone version are you using?
