### ISSUE TITLE
Lecture Checkin

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goal#93]
Therapy box to do prototype for this (speak to Tom if not).

Michael to do API.

**Comment by mparker-tbox** [comment]
Done

**Comment by michaelwebbjisc** [comment]
Needs to be added to a feature branch.  Demo on 7th Apri

**Comment by tomglanville** [comment]
Have created **feature/check-in** branches on both platforms ready for this.

**Comment by tomglanville** [comment]
This feature appears to be implemented in the **feature/check-in** branches for both platforms.

Currently tracking some UI improvements using this issue: https://github.com/jiscdev/study-goal/issues/124
